from database.connection import (
    engine,
    init_db,
    get_or_create_user,
    get_user_by_id,
    get_profile,
    update_profile,
    set_profile_ready,
    like_and_match,
    get_deck_profiles,
    get_match_partner,
    get_user_matches,
    get_active_subscription,
    activate_premium,
    revoke_premium_payment,
    record_referral,
    get_referral_count,
    set_profile_hidden,
    is_profile_hidden,
    delete_user_account,
    create_report,
    block_user,
)
from database.models import (
    Base,
    Block,
    User,
    Profile,
    Like,
    Match,
    Message,
    ProcessedPayment,
    Referral,
    Subscription,
)

__all__ = [
    "engine",
    "init_db",
    "get_or_create_user",
    "get_user_by_id",
    "get_profile",
    "update_profile",
    "set_profile_ready",
    "like_and_match",
    "get_deck_profiles",
    "get_match_partner",
    "get_user_matches",
    "get_active_subscription",
    "activate_premium",
    "revoke_premium_payment",
    "record_referral",
    "get_referral_count",
    "set_profile_hidden",
    "is_profile_hidden",
    "delete_user_account",
    "create_report",
    "block_user",
    # Модели переэкспортируются осознанно: пакет database — единая точка входа
    # к слою данных бота. В __all__ они внесены явно, чтобы это было решением,
    # а не выглядело забытым импортом.
    "Base",
    "Block",
    "User",
    "Profile",
    "Like",
    "Match",
    "Message",
    "ProcessedPayment",
    "Referral",
    "Subscription",
]
