"""стрик общения + revive

Revision ID: 2c922904b54a
Revises: d1a7c53f8e64
Create Date: 2026-08-10 14:32:27.965599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c922904b54a'
down_revision: Union[str, Sequence[str], None] = 'd1a7c53f8e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dating_chat_streaks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('streak_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_counted_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revives_left', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('revives_refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['dating_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', name='uq_chat_streak_match')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dating_chat_streaks')
    # ### end Alembic commands ###
