"""подарок подписки

Revision ID: ca5dab2e898b
Revises: 2c922904b54a
Create Date: 2026-08-10 15:01:00.375032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5dab2e898b'
down_revision: Union[str, Sequence[str], None] = '2c922904b54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dating_gift_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('buyer_user_id', sa.String(), nullable=False),
    sa.Column('recipient_user_id', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['dating_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['dating_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dating_gift_subscriptions')
    # ### end Alembic commands ###
